# Generated by Django 6.0.8 on 2026-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACT_CHECKER', 'Fact Checker'), ('FIELD_REPORTER', 'Field Reporter'), ('LEGAL_EXPERT', 'TFGBV / Legal Expert')], default='FIELD_REPORTER', max_length=20),
        ),
    ]
