# Generated by Django 6.0.8 on 2026-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('VOTER_SUPPRESSION', 'Voter Suppression'), ('DISINFORMATION', 'Disinformation / Fake News'), ('TFGBV', 'Tech-Facilitated Gender-Based Violence'), ('LOGISTICS_FAILURE', 'Logistics / Equipment Failure'), ('VIOLENCE', 'Violence / Intimidation'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('RESOLVED', 'Resolved'), ('FALSE', 'False Report')], default='PENDING', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
