# Generated by Django 6.0.8 on 2026-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident_type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_tfgbv',
            field=models.BooleanField(default=False),
        ),
    ]
