# Generated by Django 6.0.8 on 2026-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_rename_incident_type_incident_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='title_pcm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='title_yo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('VOTER_SUPPRESSION', 'Voter Suppression'), ('DISINFORMATION', 'Disinformation / Fake News'), ('TFGBV', 'Tech-Facilitated Gender-Based Violence'), ('LOGISTICS_FAILURE', 'Logistics / Equipment Failure'), ('VIOLENCE', 'Violence / Intimidation'), ('INEC', 'INEC'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED TRUE', 'Verified True'), ('MISLEADING', 'Misleading'), ('FALSE', 'False Report'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
