# Generated by Django 6.0.8 on 2026-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_summary_en_incident_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='summary_pcm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='summary_yo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title_pcm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title_yo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
