# Generated by Django 6.0.8 on 2026-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_summary_pcm_incident_summary_yo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='claim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='claim_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='claim_pcm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='claim_yo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified True'), ('MISLEADING', 'Misleading'), ('FALSE', 'False Report'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
