# Generated by Django 6.0.8 on 2026-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_claim_incident_claim_en_incident_claim_pcm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('content', models.TextField()),
                ('keyword_tracked', models.CharField(help_text="The keyword that triggered this listener (e.g., 'rigged', 'fake')", max_length=100)),
                ('sentiment', models.CharField(default='negative', max_length=20)),
                ('is_flagged', models.BooleanField(default=True, help_text='True if this post needs fact-checker attention')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
