# Generated by Django 6.0.8 on 2026-08-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_socialpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='claim_en',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='claim_pcm',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='claim_yo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='summary_pcm',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='summary_yo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title_pcm',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title_yo',
        ),
    ]
