# Generated by Django 6.0.8 on 2026-08-19 15:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_remove_incident_claim_en_remove_incident_claim_pcm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='fact_check_analysis',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Formatted report, blockquotes, and analysis produced by fact-checkers', null=True, verbose_name='Fact-Check Writeup'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(help_text='Raw incident description submitted by user'),
        ),
    ]
