# Generated by Django 6.0.8 on 2026-08-20 11:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_fact_check_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='fact_check_analysis',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_links',
            field=models.TextField(blank=True, help_text='4. Evidence & Context Links', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='where_and_when',
            field=models.CharField(blank=True, help_text='3. Where & When?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='who_said_it',
            field=models.CharField(blank=True, help_text='2. Who Said It?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='claim',
            field=models.TextField(default='No claim provided', help_text='1. The Statement / Claim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published (Fact-Checked)'), ('REJECTED', 'Rejected (Spam/Unverifiable)')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='FactCheckArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for the live feed', max_length=255)),
                ('byline', models.CharField(help_text="The author's name to display on the frontend (e.g., 'By: Eniola Amadu')", max_length=255)),
                ('verdict', models.CharField(choices=[('FALSE', 'False'), ('MISLEADING', 'Misleading'), ('TRUE', 'Verified True')], help_text='This drives the red rubber stamp on the frontend', max_length=20)),
                ('featured_image', models.ImageField(blank=True, help_text='The main picture displayed on the live feed.', null=True, upload_to='fact_checks/hero_images/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Formatted report, blockquotes, and analysis produced by fact-checkers', verbose_name='Fact-Check Writeup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact_checker', models.ForeignKey(help_text='Internal user who created this in the dashboard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('related_incidents', models.ManyToManyField(blank=True, help_text='Link the raw citizen tips that provided evidence for this article', related_name='fact_checks', to='incidents.incident')),
            ],
        ),
    ]
