# Generated by Django 6.0.8 on 2026-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_remove_incident_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reporter',
        ),
        migrations.AlterField(
            model_name='incident',
            name='claim',
            field=models.TextField(help_text='The Statement / Claim'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='evidence_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='where_and_when',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='who_said_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
